### ISSUE TITLE
Position Slider outside of grid

### ISSUE THREAD

**Issue by dunland** [dunland/cspy#9]
![Screenshot from 2021-11-12 11-05-02](https://user-images.githubusercontent.com/23742320/141449218-d6ca45e1-0f66-45bf-ae27-b75fc57fa753.png)

Slider is inside of grid → this renders the lower grid rows unnecessary.

Constraining the grid to `grid_height - slider_y` could help rendering the slider below the grid could solve this.

**Comment by cqx931** [comment]
I think it's the block_size that needs to be changed here. 
https://github.com/dunland/cspy/blob/master/cityscopy.py#L236

Right now the block size is calculated based on video_res and the grid dimension. However, the height of the block_size shouldn't be based on video_res[1] / grid_dim[1] any more when the range of grid analysis (20 rows) no longer covers the full video range(22 rows).

I have pushed my changes to the branch: sliderPosition: https://github.com/dunland/cspy/tree/sliderPosition

**Comment by cqx931** [comment]
Render the grid to `slider.y - block_size[1]/2`, if video.y < 1080, calculate it according to ratio.

**Comment by cqx931** [comment]
https://github.com/dunland/cspy/tree/sliderPosition
Please check a new attempt for slider position issue

- passing video res variable to sliders if real sense is not in use
- fix grid position according to `self.sliders[0].y`

**Comment by dunland** [comment]
![Screenshot from 2021-12-14 08-57-30](https://user-images.githubusercontent.com/23742320/145956397-b43a66da-acc3-4a6b-a08b-8af14ce6e215.png)
hey.. das scheint zu klappen! :clinking_glasses: 

das Grid ist nun abhängig von der absoluten Slider-Position? Das wäre ja auch etwas eigenartig. Im besten Fall haben die beiden Elemente nichts miteinander zu tun..

![Screenshot from 2021-12-14 08-58-56](https://user-images.githubusercontent.com/23742320/145956788-555b7a22-d285-4de7-967e-daf2064999a1.png)

**Comment by dunland** [comment]
ich habe übrigens noch ein kleines Chaos veranstaltet mit diversen changes & merges.. also bitte nochmal das update auf `sliderPosition` herunterladen!

**Comment by cqx931** [comment]
https://github.com/dunland/cspy/commit/0b3af30187526781f5648fe9cb48cc49b63eb88f
Ich habe jetzt zwei weitere Parameter in cityscopy.json hinzugefügt: `grid_w` und `grid_h`.

**Comment by dunland** [comment]
nice!
ich habe `sliderPosition` jetzt in den `master` branch gezogen ✓
